Add rpmsg-echo-test example
OpenAMP/openamp-system-reference pull request #1
Opened 2022-09-23 21:30 UTC by TanmayShah-xilinx

rpmsg-echo-test example demonstrates how to write linux userspace application that uses rpmsg devices in kernel space. This application sends pre-defined payload to remote processor firmware and waits for remote processor to send same payload back. It then verifies received payload integrity. Number of packets to send to remote processor can be configured from command line

Signed-off-by: Tanmay Shah <tanmay.shah@amd.com>

2022-09-26 13:37 UTC, arnopo requested changes

2022-09-26 13:37 UTC, arnopo commented on examples/linux/rpmsg-echo-test/echo_test.c
> + */
An README.txt would be nice to explain the test and what is needed on remote side ( compatible plaftform, associated remoteproc project...)

2022-09-26 16:00 UTC, TanmayShah-xilinx commented on Makefile
> +TARGETS := all clean
Ok I will remove it. I agree for now we don't have to push generic makefile yet.

2022-09-26 16:01 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-echo-test/echo_test.c
> + */
Thanks. Yes that makes sense. I will add such README.

2022-09-26 17:23 UTC, TanmayShah-xilinx commented on Makefile
> +TARGETS := all clean
Yes. This is old demo where by default dst buffer was picked up by driver from memory-region (vring). We have some new patch that allows to set destination buffer from command line. I will create new pull request accordingly.

2022-09-26 17:36 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-echo-test/echo_test.c
> +	if (ret) {
Yes. This is old demo where for 0xFFFFFFFF  dst address, by default driver picked up from memory-region (vrings). We have some new patch that allows to set destination buffer from command line which sets it in sysfs. I will create new pull request that has latest source code as well.

2022-09-27 07:19 UTC, arnopo commented on examples/linux/rpmsg-echo-test/echo_test.c
> +	if (ret) {
Is there a reason to create a specific RP for these patches? Perhaps you could merge them in the code or add these patches into this PR.
Since this code should become a reference code for the use of rpmsg_char for Linux, I would expect it to be compatible with the latest version of Linux.

2022-09-27 13:48 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-echo-test/echo_test.c
> +	if (ret) {
Yes I will squash all the patches in same PR. Also, demos are compatible with latest version of linux.

2022-09-28 01:06 UTC, TanmayShah-xilinx commented
I will close this pull request and open new one as new echo_test app contains more changes.

2022-09-28 17:19 UTC, TanmayShah-xilinx commented
As discussed this with Arnaud same pull request can be used.

2022-09-28 17:30 UTC, TanmayShah-xilinx commented
@arnopo 

I addressed comments in latest commit.
- No makefile in root dir
- Add README for echo_test
- Allow end point dst address to be set from command line.

2022-10-03 09:48 UTC, arnopo approved these changes

2022-10-04 02:32 UTC, edmooring approved these changes
Looks good to me.

2022-10-04 09:48 UTC, arnopo commented on examples/linux/rpmsg-echo-test/echo_test.c
> +int rpmsg_create_ept(int rpfd, struct rpmsg_endpoint_info *eptinfo)
Please rename this function, that introduce confusing as already defined in the open-amp library

2022-10-06 05:45 UTC, TanmayShah-xilinx commented
@wmamills, @arnopo, @edmooring 

I have split changes in different commits as requested. If all look good, I will do the same for other examples as well.

2022-10-06 14:32 UTC, arnopo commented
> @wmamills, @arnopo, @edmooring
> 
> I have split changes in different commits as requested. If all look good, I will do the same for other examples as well.

look good to me
Thanks for the extra work

2022-10-10 12:17 UTC, wmamills requested changes
Reference should be to the openamp lib example not the Xilinx sample

2022-10-10 17:24 UTC, TanmayShah-xilinx commented
> Reference should be to the openamp lib example not the Xilinx sample

Ah! I understand now. That would be: https://github.com/OpenAMP/open-amp/blob/main/apps/examples/echo/rpmsg-echo.c

I will update README accordingly in all the examples.

2022-10-21 20:18 UTC, TanmayShah-xilinx commented
> > Reference should be to the openamp lib example not the Xilinx sample
> 
> Ah! I understand now. That would be: https://github.com/OpenAMP/open-amp/blob/main/apps/examples/echo/rpmsg-echo.c
> 
> I will update README accordingly in all the examples.

Done.

2022-10-26 23:15 UTC, TanmayShah-xilinx commented
@arnopo , @edmooring 
Could you please look at latest change ?
I can only re-request review for one of you.
I am not sure why I can't re-request reviews for both of you.

2022-10-28 12:08 UTC, arnopo approved these changes

2022-10-28 15:02 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-echo-test/echo_test.c
> +	charfd = get_rpmsg_chrdev_fd(rpmsg_ctrl_dev_name, rpmsg_char_name);
Yes correct, I will add modprobe(rpmsg_ctrl.ko) in system command. 
When I tested with 6.0, built rpmsg_* drivers as part of kernel so I didn't see that issue.

Thanks.

2022-11-04 09:34 UTC, arnopo approved these changes
LGTM

2022-11-15 08:16 UTC, merged