WIP: examples: rpmsg_over_ivshmem: add RPMsg over IVSHMEM sample code.
OpenAMP/openamp-system-reference pull request #11
Opened 2023-06-21 19:54 UTC by uLipe

The additions include a backend to glue the Zephyr IVSHMEM device driver into the openAMP code making it usable to send data between two QEMU instances using the RPMsg protocol.

Also a custom shell command in the host side application is provided to send string messages for a number of times allowing to perform stress test of the communication.

This sample has a limitation regarding the order of initialization of the QEMU host and side instances, the host side must be initialized first, followed by the remote side please refer the README of this sample for more info.

2023-06-21 19:55 UTC, uLipe commented
This PR is a work in progress but I would like to share with even in this state in order to give a follow up of this work.

2023-06-21 19:58 UTC, uLipe commented on west.yml
> +      url-base: https://github.com/zephyrproject-rtos
At this point the additions from the 3.4 branch were not available into the zephyr staging project from the openAMP repository, so this is a temporary solution that will be removed once 3.4 becomes available.

The 3.4 branch is needed in order to have IVSHMEM driver and some fixes for the PCIe controller for ARM.

2023-06-21 19:59 UTC, uLipe commented on examples/zephyr/rpmsg_over_ivshmem/rpmsg_ivshmem_backend/rpmsg_ivshmem_backend.c
> +#ifdef CONFIG_OPENAMP_MASTER
This is something that needs to be changed in zephyr itself, I know this symbol is deprecated in the openAMP code base, but Zephyr module interface KCONFIG redefines this symbol and it is used in any glue code between Zephyr and openAMP.

2023-06-22 15:01 UTC, uLipe commented
@wmamills , @danmilea , @arnopo just tagging you to follow-up, but feel free to review and reproduce this one.

2023-06-26 07:41 UTC, arnopo reviewed
2 minor comments else LGTM

2023-06-26 07:41 UTC, arnopo commented on examples/zephyr/dual_qemu_ivshmem/rpmsg_ivshmem_backend/rpmsg_ivshmem_backend.c
> +	+1;
nitpicking  
`peer_dest_id += 1; `would be more readable
Else to add a space between '+' an '1'

2023-06-26 07:41 UTC, arnopo commented on west.yml
> +      import: true
Would be better to update west.yml in a separate patch.

2023-06-29 07:35 UTC, arnopo approved these changes
It seems that a coding rule in Zephyr is to put the code in the `src` folder.  This could be the case for the rpmsg_ivshmem_backend folder, but keeping it that way works for me too.

2023-06-29 15:16 UTC, TanmayShah-xilinx reviewed
Hello,

Thanks for your patch.
minor comments related to coding style, otherwise looks good to me.

Thanks,
Tanmay

2023-06-29 15:16 UTC, TanmayShah-xilinx commented on examples/zephyr/dual_qemu_ivshmem/rpmsg_ivshmem_backend/rpmsg_ivshmem_backend.c
> +LOG_MODULE_REGISTER(LOG_MODULE_NAME);
can we move LOG_* macros after header files ? This way we don't have to include log.h file separately.

2023-06-29 15:16 UTC, TanmayShah-xilinx commented on examples/zephyr/dual_qemu_ivshmem/rpmsg_ivshmem_backend/rpmsg_ivshmem_backend.c
> + * SPDX-License-Identifier: Apache-2.0
I don't know too much about including license information, but above main.c has BSD-3-Clause, and here Apache-2.0. I don't know the difference, but should we unify licenses for all source files? @arnopo, @wmamills what is the guideline here?

2023-06-29 15:16 UTC, TanmayShah-xilinx commented on examples/zephyr/dual_qemu_ivshmem/rpmsg_ivshmem_backend/rpmsg_ivshmem_backend.c
> +#include <string.h>
standard header files at the top. @arnopo Do we follow coding style from openamp library or zephyr RTOS coding style?

2023-06-29 15:37 UTC, arnopo commented on examples/zephyr/dual_qemu_ivshmem/rpmsg_ivshmem_backend/rpmsg_ivshmem_backend.c
> + * SPDX-License-Identifier: Apache-2.0
Zephyr is apache-2.0, 
openamp is BSD-3

I would say as it is Zephyr application, would be better to be Apache 2.0

2023-07-03 13:56 UTC, uLipe commented on examples/zephyr/dual_qemu_ivshmem/rpmsg_ivshmem_backend/rpmsg_ivshmem_backend.c
> +LOG_MODULE_REGISTER(LOG_MODULE_NAME);
This pattern is the required pattern from Zephyr for registering a LOG capable module, the both defines are consumed by the header file and then in the order, by the LOG registering macro.

2023-07-03 16:33 UTC, arnopo commented on examples/zephyr/dual_qemu_ivshmem/rpmsg_ivshmem_backend/rpmsg_ivshmem_backend.c
> + * SPDX-License-Identifier: Apache-2.0
@uLipe : Please could you replace BSD by Apache license in your dev?

2023-07-03 16:37 UTC, uLipe commented on examples/zephyr/dual_qemu_ivshmem/rpmsg_ivshmem_backend/rpmsg_ivshmem_backend.c
> + * SPDX-License-Identifier: Apache-2.0
Sure, thanks for clarify.

2023-07-03 16:37 UTC, arnopo commented on examples/zephyr/dual_qemu_ivshmem/README.rst
> +OpenAMP RPMSG over IVSHMEM system reference sample
based on  other in-tree Zephyr examples, it is not necessary to add a License here

2023-07-04 15:30 UTC, uLipe commented on examples/zephyr/dual_qemu_ivshmem/host/boards/pcie_ivshmem.dtsi
> +			vendor-id = <0x1af4>;
I searched for this vendor ID in the PCI-SIG group list and it did not return results, it seems this was just assigned randomly on the zephyr in-tree sample:

https://github.com/zephyrproject-rtos/zephyr/blob/690b21718ae67a972b442dc98c9eccc3f140df0c/samples/drivers/virtualization/ivshmem/doorbell/boards/pcie_ivshmem.dtsi#L13

2023-07-05 09:59 UTC, arnopo commented on examples/zephyr/dual_qemu_ivshmem/rpmsg_ivshmem_backend/rpmsg_ivshmem_backend.c
> + * SPDX-License-Identifier: Apache-2.0
It seems that there are still other headers with the BSD license that have not been updated

2023-07-05 14:25 UTC, TanmayShah-xilinx commented on examples/zephyr/dual_qemu_ivshmem/rpmsg_ivshmem_backend/rpmsg_ivshmem_backend.c
> +LOG_MODULE_REGISTER(LOG_MODULE_NAME);
Ok sounds good.

2023-07-05 14:28 UTC, TanmayShah-xilinx commented on examples/zephyr/dual_qemu_ivshmem/host/boards/pcie_ivshmem.dtsi
> +			vendor-id = <0x1af4>;
Ok. It's good to mention in README that vendor-id is random and taken from zephyr os (may be with its version number).

2023-07-05 14:35 UTC, TanmayShah-xilinx approved these changes
LGTM. Just can we mention vendor-id was taken from zephyr-(version) in README ? That will be good for user to understand how vendor-id is defined.

2023-07-05 16:15 UTC, uLipe commented on examples/zephyr/dual_qemu_ivshmem/host/boards/pcie_ivshmem.dtsi
> +			vendor-id = <0x1af4>;
Put a note on README regarding the Vendor-ID

2023-07-13 07:22 UTC, arnopo commented
@uLipe I run zephyr checkpatch.pl on your PR. there are some errors reported... could you fix them, please?

@TanmayShah-xilinx: any new concerns on this PR?

2023-07-13 13:09 UTC, uLipe commented
@arnopo , yes sure, I will fix and run checkpatch.pl before pushing again

2023-07-17 13:34 UTC, uLipe commented
@arnopo , @TanmayShah-xilinx  just adressed the zephyr style issues.

2023-07-17 14:36 UTC, arnopo reviewed
I still have issues with checkpatch.
could you squash the fixes and re-run  the checkpatch?

2023-07-17 15:44 UTC, uLipe commented on examples/zephyr/dual_qemu_ivshmem/rpmsg_ivshmem_backend/rpmsg_ivshmem_backend.h
> +struct rpmsg_device* get_rpmsg_ivshmem_device(void);
My bad, I skipped this file when running it.

2023-07-17 16:05 UTC, uLipe commented on examples/zephyr/dual_qemu_ivshmem/rpmsg_ivshmem_backend/rpmsg_ivshmem_backend.h
> +struct rpmsg_device* get_rpmsg_ivshmem_device(void);
and done!

2023-07-18 07:18 UTC, arnopo requested changes
Please keep a separate patch for the update of the zephyr version.  FYI in OpenAMp we use to fix the issue in the commit directly an not add fixup! on top of the series during review step

Please , could you fix the isfollowing remaining issue report by checkpatch 

CHECK: Blank lines aren't necessary after an open brace '{'
#462: FILE: examples/zephyr/dual_qemu_ivshmem/host/src/main.c:21:
+{
+

WARNING: line length of 102 exceeds 10 columns
#496: FILE: examples/zephyr/dual_qemu_ivshmem/host/src/main.c:55:
+	printf("Hello %s - Host Side, the communication over RPMsg is ready to use!\n", CONFIG_BOARD);

CHECK: Alignment should match open parenthesis
#500: FILE: examples/zephyr/dual_qemu_ivshmem/host/src/main.c:59:
+static int cmd_rpmsg_ivshmem_send(const struct shell *sh,
+			   size_t argc, char **argv)

WARNING: line length of 109 exceeds 80 columns
#516: FILE: examples/zephyr/dual_qemu_ivshmem/host/src/main.c:75:
+			printf("failed to send message over RPMsg-IVSHMEM to the Remote side: %d\n", status);


CHECK: Alignment should match open parenthesis
#534: FILE: examples/zephyr/dual_qemu_ivshmem/host/src/main.c:93:
+SHELL_STATIC_SUBCMD_SET_CREATE(sub_rpmsg_ivshmem,
+						SHELL_CMD_ARG(send, NULL,

CHECK: Alignment should match open parenthesis
#535: FILE: examples/zephyr/dual_qemu_ivshmem/host/src/main.c:94:
+						SHELL_CMD_ARG(send, NULL,
+								"Usage: rpmsg_ivshmem send <string> <number of messages>",


CHECK: Alignment should match open parenthesis
#541: FILE: examples/zephyr/dual_qemu_ivshmem/host/src/main.c:100:
+SHELL_CMD_ARG_REGISTER(rpmsg_ivshmem, &sub_rpmsg_ivshmem,
+				"Commands to use RPMsg over IVSHMEM",

WARNING: 'supress' may be misspelled - perhaps 'suppress'?
#643: FILE: examples/zephyr/dual_qemu_ivshmem/remote/prj.conf:16:
+# Enable IVSHMEM shell when debugging the driver, default OFF to supress warnings when not used.

WARNING: line length of 104 exceeds 100 columns
#705: FILE: examples/zephyr/dual_qemu_ivshmem/remote/src/main.c:53:
+	printf("Hello %s - Remote Side, the communication over RPMsg is ready to use!\n", CONFIG_BOARD);

CHECK: No space is necessary after a cast
#760: FILE: examples/zephyr/dual_qemu_ivshmem/rpmsg_ivshmem_backend/rpmsg_ivshmem_backend.c:48:
+			.virt       = (void *) 0,

CHECK: Please don't use multiple blank lines
#921: FILE: examples/zephyr/dual_qemu_ivshmem/rpmsg_ivshmem_backend/rpmsg_ivshmem_backend.c:209:
+
+

CHECK: Alignment should match open parenthesis
#927: FILE: examples/zephyr/dual_qemu_ivshmem/rpmsg_ivshmem_backend/rpmsg_ivshmem_backend.c:215:
+	k_thread_create(&ivshmem_ev_loop_thread,
+		ivshmem_ev_loop_stack,

2023-07-19 00:04 UTC, uLipe commented
It is strange, my checkpatch.pl (under zephyr/scripts) did not catch these style issues, I addressed them manually btw.

2023-07-20 16:39 UTC, uLipe commented
@arnopo , PTAL again, I ran the checkpatch using the same command you are using, the remaining issues are gone, but it stills report duplicate sign-off, I checked manually the patch and I did not find a reason for this being reported.

2023-07-20 17:12 UTC, uLipe commented
It is strange, no matter how I align these, or change my editor settings, these three error never disappear, I even copied the alignment from other Zephyr samples and subsystems with no luck, as well trying to align mixing spaces and tabs, is there something I'm missing? @arnopo

2023-07-20 17:37 UTC, arnopo commented on examples/zephyr/dual_qemu_ivshmem/host/src/main.c
> +
For instance here you align only with tabs, you have also to use space to complete alignment.  
And be sure that you configure your editor using 8 spaces for a tab.
 
```c
 SHELL_STATIC_SUBCMD_SET_CREATE(sub_rpmsg_ivshmem,
-				SHELL_CMD_ARG(send, NULL,
-						"Usage: rpmsg_ivshmem send <string> <number of messages>",
-						cmd_rpmsg_ivshmem_send, 3, 0),
-				SHELL_SUBCMD_SET_END
+			       SHELL_CMD_ARG(send, NULL,
+					     "Usage: rpmsg_ivshmem send <string> <number of messages>",
+					     cmd_rpmsg_ivshmem_send, 3, 0),
+			       SHELL_SUBCMD_SET_END
 		);

 SHELL_CMD_ARG_REGISTER(rpmsg_ivshmem, &sub_rpmsg_ivshmem,
-				"Commands to use RPMsg over IVSHMEM",
-				cmd_rpmsg_ivshmem_send, 3, 0);
+		       "Commands to use RPMsg over IVSHMEM",
+		       cmd_rpmsg_ivshmem_send, 3, 0);
```
If you don't succeed, I'll correct the problem during the merge.

2023-07-20 21:20 UTC, uLipe commented
@arnopo the problem was in my editor local config, I was able to fix the alignment warning, thank you.

2023-07-21 11:56 UTC, arnopo approved these changes
LGTM

2023-08-02 17:09 UTC, TanmayShah-xilinx approved these changes
LGTM

2023-08-05 00:08 UTC, TanmayShah-xilinx commented
@wmamills if all look good, can we merge this change? Me and @arnopo have approved.

2023-08-17 07:26 UTC, merged