Refactor example code
OpenAMP/openamp-system-reference pull request #12
Opened 2023-07-12 19:49 UTC by glneo

This helps make these example files shorter and less intimidating for new users. Useful when trying to showcase OpenAMP to new users and teams.

2023-07-13 07:31 UTC, arnopo commented on examples/linux/rpmsg-echo-test/echo_test.c
> +#include "../common/common.h"
you can remove the include of<sys/ioctl.h>

2023-07-18 07:21 UTC, arnopo commented
@TanmayShah-xilinx : could you confirm that the PR does not introduce regression on your platform?

2023-07-18 07:31 UTC, arnopo requested changes

2023-07-18 07:31 UTC, arnopo commented on examples/linux/common/common.c
> +		return -EINVAL;
Could you take opportunity to better manage error case?
in case of error in this function,  would be better to close the file before return

2023-07-18 07:31 UTC, arnopo commented on examples/linux/common/common.c
> +				return fd;
same in this function the directory is not closed

2023-07-18 21:28 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-echo-test/Makefile
> +APP_OBJS = echo_test.o ../common/common.o
Thanks for your patch.

We should include common.o in clean target as well.
So when we do make clean, it re-builds common.o as well.
or probably introduce new target (distclean), that will remove common.o as well. clean will only remove local directory *.o and distclean will remove all dependencies as well such as common.o. I am fine with either approach.

Thanks.

2023-07-18 22:16 UTC, TanmayShah-xilinx reviewed
LGTM

2023-07-18 22:22 UTC, TanmayShah-xilinx commented
> @TanmayShah-xilinx : could you confirm that the PR does not introduce regression on your platform?

@arnopo I verified matrix multiply and proxy app demo. It is working fine without introducing regressions on zcu102 qemu platform. I have some comments, but apart from that it looks good to me.

2023-07-19 18:52 UTC, glneo commented on examples/linux/common/common.c
> +				return fd;
Looks like it is closed on line 127 above.

2023-07-19 18:52 UTC, glneo commented on examples/linux/common/common.c
> +		return -EINVAL;
Right now this is an exact copy/paste without change from before. I'll add a new patch on top to fix this.

2023-07-19 18:55 UTC, glneo commented on examples/linux/rpmsg-echo-test/Makefile
> +APP_OBJS = echo_test.o ../common/common.o
I'll add 'distclean'. I'm not sure how the 'clean' option would interact when one wanted only to clean the current project.

Fixing out of tree builds (or using CMake or similar) would fix all that, but that would be a task for another day :)

2023-07-19 21:28 UTC, TanmayShah-xilinx approved these changes

2023-07-20 11:28 UTC, arnopo commented on examples/linux/common/common.c
> +				return fd;
I had missed it, thanks for pointing it out.

2023-07-20 11:31 UTC, arnopo approved these changes
LGTM

2023-07-21 12:26 UTC, merged