examples: zephyr: add qemu_cortex_r5 board support
OpenAMP/openamp-system-reference pull request #14
Opened 2023-07-31 19:57 UTC by TanmayShah-xilinx

Add dt overlay with zephyr,ipc and zephyr,ipc_shm nodes for AMD-xilinx zynqmp platform.

This PR depends on and should be merged after Zephy IPM driver PR: https://github.com/zephyrproject-rtos/zephyr/pull/61008

2023-08-15 18:43 UTC, tnmysh commented
We can review this PR now as dependent PR is merged in Zephyr: https://github.com/zephyrproject-rtos/zephyr/pull/61008

2023-08-17 07:54 UTC, arnopo requested changes

2023-08-17 07:54 UTC, arnopo commented on examples/zephyr/rpmsg_multi_services/src/prj.conf
> +CONFIG_XLNX_IPM=y
This is board specific, you have to create a  boards/qemu_cortex_r5.conf to declare it
you can have a look here for some examples:
https://elixir.bootlin.com/zephyr/latest/source/samples/subsys/ipc/openamp/boards

2023-08-17 07:54 UTC, arnopo commented on examples/zephyr/rpmsg_multi_services/boards/qemu_cortex_r5.overlay
> + * Copyright (c) 2019 Lexmark International, Inc.
Not sur that you need to keep it

2023-08-21 21:52 UTC, tnmysh commented on examples/zephyr/rpmsg_multi_services/boards/qemu_cortex_r5.overlay
> + * Copyright (c) 2019 Lexmark International, Inc.
Thanks. I will remove it.d

2023-08-25 14:29 UTC, tnmysh commented on examples/zephyr/rpmsg_multi_services/src/prj.conf
> +CONFIG_XLNX_IPM=y
@arnopo Thanks for reviews. I removed this option from here. It will be picked up by zephyr based on if device-tree has XLNX IPI compatible node or not. So we don't need here.

2023-08-28 16:37 UTC, tnmysh commented on examples/zephyr/rpmsg_multi_services/boards/qemu_cortex_r5.overlay
> + */
Ok, I will fix it.

2023-08-30 20:51 UTC, tnmysh commented on examples/zephyr/rpmsg_multi_services/boards/qemu_cortex_r5.overlay
> + */
Done.

2023-08-31 12:22 UTC, arnopo approved these changes

2023-09-07 13:49 UTC, tnmysh commented
@edmooring could you please review it?

2023-09-08 03:22 UTC, edmooring approved these changes
Looks good to me.

2023-09-11 07:41 UTC, merged