examples: add apps that uses rpmsg in kernelspace
OpenAMP/openamp-system-reference pull request #2
Opened 2022-10-04 04:59 UTC by TanmayShah-xilinx

rpmsg-mat-mul
  This example demonstrates communication between host and remote processor
  using rpmsg in kernelspace

rpmsg-proxy-app
  This example demonstrates use of host file system by remote processor

Signed-off-by: Tanmay Shah <tanmay.shah@amd.com>

2022-10-04 10:24 UTC, arnopo commented on examples/linux/rpmsg-proxy-app/README
> +  https://github.com/Xilinx/embeddedsw/tree/xlnx_rel_v2022.1/lib/sw_apps/openamp_rpc_demo
Only a question, not a request for this PR
Do you think that on remote side this demo could be adapted to use the [rpmsg rpc service](https://github.com/OpenAMP/open-amp/tree/main/lib/service/rpmsg/rpc) instead?
The main difference is that the proxy is based only on operating system API, while the rpc service is more generic.

2022-10-04 10:24 UTC, arnopo commented on examples/linux/rpmsg-proxy-app/proxy_app.c
> +		.name = "rpmsg-openamp-demo-channel", .src = 0, .dst = 0
All the channels has this name, that means that it is not possible to multiplex the demos, right?

2022-10-04 10:24 UTC, arnopo commented on examples/linux/rpmsg-mat-mul/README
> +  https://github.com/Xilinx/embeddedsw/tree/xlnx_rel_v2022.1/lib/sw_apps/openamp_matrix_multiply
I can not figure out what this demo demonstrate in addition of the "rpmsg-echo-test example" proposed in https://github.com/OpenAMP/openamp-system-reference/pull/1
I means from the IPC perspective, having just an echo or a processing on remote side seems to me the same usecase... but perhaps i missed something?

It could be interesting to base it on the https://github.com/OpenAMP/open-amp/tree/main/lib/service/rpmsg/rpc or/and to use the rpmsg_ioctl RPMSG_CREATE_DEV_IOCTL to initiate the communication from the Linux side with an NS announcement. 

Anyway let's first @edmooring and @wmamills shar their view on this example

2022-10-04 20:49 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-proxy-app/README
> +  https://github.com/Xilinx/embeddedsw/tree/xlnx_rel_v2022.1/lib/sw_apps/openamp_rpc_demo
We can introduce new demo that uses rpc service and keep this one as it is.

2022-10-04 20:52 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-proxy-app/proxy_app.c
> +		.name = "rpmsg-openamp-demo-channel", .src = 0, .dst = 0
Multiplex do you mean run them simultaneously ? Yes I believe we can't do that.

2022-10-04 20:54 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-mat-mul/README
> +  https://github.com/Xilinx/embeddedsw/tree/xlnx_rel_v2022.1/lib/sw_apps/openamp_matrix_multiply
You are correct. Both demonstrate IPC communication. However, mat_mul_demo shows simple IPC communication, where as echo_test shows it is possible to send/receive various size of payloads really fast between Host and Remote without data corruption or loss. But the end goal is to demonstrate IPC mechanism.

2022-10-04 20:56 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-proxy-app/README
> +app: proxy_app
Ack.

2022-10-04 20:57 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-proxy-app/README
> +  https://github.com/Xilinx/embeddedsw/tree/xlnx_rel_v2022.1/lib/sw_apps/openamp_rpc_demo
Do you mean in the README of this demo or code of remote side firmware?
Could you please point which information to fix?

2022-10-04 20:57 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-mat-mul/mat_mul_demo.c
> +int rpmsg_create_ept(int rpfd, struct rpmsg_endpoint_info *eptinfo)
Ack.

2022-10-10 12:25 UTC, wmamills requested changes
What is the resolution of channel name discussion?
Each demo should have its own name right?
Running multiple versions of each demo is not needed but it should be possible (if not done today) to create one firmware that works with all 3 Linux examples

2022-10-12 03:06 UTC, TanmayShah-xilinx commented
> What is the resolution of channel name discussion?

So, each demo is using same channel name for now, but it is possible to run multiple demos simultaneously with different channel name. It is also possible to give destination endpoint address from command line. 

> Each demo should have its own name right?

Yes if we want to run them simultaneously. This is needed specially when RPU is in split mode.

> Running multiple versions of each demo is not needed but it should be possible (if not done today) to create one firmware that works with all 3 Linux examples

Yes it is possible.

2022-10-12 22:21 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-proxy-app/README
> +  https://github.com/Xilinx/embeddedsw/tree/xlnx_rel_v2022.1/lib/sw_apps/openamp_rpc_demo
@arnopo I will explicitly mention that proxy service is used on Host side.

2022-10-12 23:15 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-proxy-app/README
> +  https://github.com/Xilinx/embeddedsw/tree/xlnx_rel_v2022.1/lib/sw_apps/openamp_rpc_demo
@arnopo I fixed description in remote side file with this pull request: https://github.com/OpenAMP/open-amp/pull/429

2022-10-21 20:20 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-mat-mul/mat_mul_demo.c
> +int rpmsg_create_ept(int rpfd, struct rpmsg_endpoint_info *eptinfo)
Done.

2022-10-21 20:20 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-proxy-app/proxy_app.c
> +static int rpmsg_create_ept(int rpfd, struct rpmsg_endpoint_info *eptinfo)
Done.

2022-10-24 08:57 UTC, arnopo reviewed
Few points, mainly on the rpmsg proxy app

2022-10-24 08:57 UTC, arnopo commented on examples/linux/rpmsg-mat-mul/README
> +  them to remote processor using rpmsg framework in kernelspace and waits for
s/and them/and send them/

2022-10-24 08:57 UTC, arnopo commented on examples/linux/rpmsg-mat-mul/README
> +  multiplies them and send result back to host processor.
s/send/sends/

2022-10-24 08:57 UTC, arnopo commented on examples/linux/rpmsg-mat-mul/mat_mul_demo.c
> +	const char *default_bin_name = "mat_mul_demo";
could you check that relacing by 	`extern char *__progname;` ( as done in rpmsg-utils) is working? this avoid to hard-code the name of the binary

2022-10-24 08:57 UTC, arnopo commented on examples/linux/rpmsg-mat-mul/mat_mul_demo.c
> +	printf("-n - number of times repeate this demo\r\n");
number of times this demo is repeated or number of times  to repeat this demo

2022-10-24 08:57 UTC, arnopo commented on examples/linux/rpmsg-proxy-app/README
> +  This app allows remote processor to use file system of host processor.  Host
double space befor `Host`

2022-10-24 08:57 UTC, arnopo commented on examples/linux/rpmsg-proxy-app/README
> +  service that is implemented on host side.
Some reference to the rpmsg proxy service which implement the stdio should be added some where.
https://github.com/OpenAMP/open-amp/blob/main/lib/proxy/rpmsg_retarget.c

2022-10-24 08:57 UTC, arnopo commented on examples/linux/rpmsg-proxy-app/README
> +  1. When the application prompts you to Enter name, enter any string without space.
Needed to specify which par is done on host and which part is done on remote

2022-10-24 08:57 UTC, arnopo commented on examples/linux/rpmsg-proxy-app/README
> +  service that is implemented on host side.
I remember that I take some times to understand this demo are comments and code are not aligned ( from my point of view)

- This demo  seems to me more a "standard IO redirection", not only use host file system. for instance the printf is also redirected. and a local  `xil_printf` is used for print on local console

- Some reference to the rpmsg proxy service which implements the stdio should be added somewhere.
https://github.com/OpenAMP/open-amp/blob/main/lib/proxy/rpmsg_retarget.c

2022-10-24 08:57 UTC, arnopo commented on examples/linux/rpmsg-proxy-app/README
> +  scanf function is used by firmware to get these inputs.
which firmware?

2022-10-24 08:57 UTC, arnopo commented on examples/linux/rpmsg-proxy-app/README
> +  After this, "printf" function is used to print these inputs on output.
not obvious, please rework the sentence

2022-10-27 05:41 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-mat-mul/mat_mul_demo.c
> +	const char *default_bin_name = "mat_mul_demo";
Yes It's working. I will update it in other examples too.

2022-10-27 19:25 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-proxy-app/README
> +  After this, "printf" function is used to print these inputs on output.
both this and line above will be removed and better explanation will be introduced.

2022-10-27 21:13 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-proxy-app/README
> +  service that is implemented on host side.
> * This demo  seems to me more a "standard IO redirection", not only use host file system. for instance the printf is also redirected. and a local  `xil_printf` is used for print on local console
> *

local xil_printf is also using same UART as of Host processor, so we will see the output on same console.

2022-10-27 21:13 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-proxy-app/README
> +  service that is implemented on host side.
Ok I will add reference to above link.

2022-10-27 21:14 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-proxy-app/README
> +  scanf function is used by firmware to get these inputs.
This would be remote processor firmware. I will fix it.

2022-10-28 08:17 UTC, arnopo commented on examples/linux/rpmsg-proxy-app/proxy_app.c
>  	printf("\r\nMaster>probe rpmsg_char\r\n");
please replace `Master` term by `host`

2022-11-09 09:06 UTC, arnopo reviewed
LGTM with minor comments

2022-11-09 09:06 UTC, arnopo commented on examples/linux/rpmsg-mat-mul/mat_mul_demo.c
> +	/* kernel >= 6.0 expects rpmsg_ctrl interface under virtio*.rpmsg_ctrl*.* dir */
s/kernel/Linux kernel/
To fix in whole file

2022-11-10 16:04 UTC, arnopo approved these changes

2022-11-15 08:17 UTC, merged