Move openamp demos
OpenAMP/openamp-system-reference pull request #44
Opened 2024-06-19 19:16 UTC by tnmysh

Move apps directory from open-amp library repo to openamp-system-reference repo and modify cmake build infra structure as needed to build these apps.

2024-06-20 16:54 UTC, arnopo reviewed
I think this is a step in the right direction to move forward. 
Just a request: please split the commit to make it simpler to compare with the original code.

i will try to rebuild and run application to test it

2024-06-20 16:54 UTC, arnopo commented on examples/legacy_apps/system/generic/machine/zynqmp_r5/linker_remote.ld
> +} > psu_ddr_S_AXI_BASEADDR
seems not aligned with open-amp lib , any reason?
see: https://github.com/OpenAMP/open-amp/blob/main/apps/system/generic/machine/zynqmp_r5/linker_remote.ld#L85

2024-06-20 16:54 UTC, arnopo commented on examples/legacy_apps/CMakeLists.txt
> +add_subdirectory (examples)
could you move the update in your second commit and just have a copy past here?

2024-06-20 16:54 UTC, arnopo commented on examples/legacy_apps/cmake/collect.cmake
> +function (collector_create name base)
same for the cmake folder please move it in a separate patch

2024-07-18 00:53 UTC, tnmysh commented on examples/legacy_apps/system/generic/machine/zynqmp_r5/linker_remote.ld
> +} > psu_ddr_S_AXI_BASEADDR
For sometime open-amp demos are being built from downstream repo, and we never got chance to modify linker script here.

Original linker script isn't working. SO I have modified it. But, looks like for now I will keep original linker script, and send separate change fixing only linker script.

2024-07-18 00:53 UTC, tnmysh commented on examples/legacy_apps/CMakeLists.txt
> +add_subdirectory (examples)
Yes, I will modify next revision accordingly.

2024-07-18 00:53 UTC, tnmysh commented on examples/legacy_apps/cmake/collect.cmake
> +function (collector_create name base)
Ack.

2024-07-19 12:14 UTC, arnopo requested changes
I tested on my Linux PC using west and cmake. Few comments and suggestions

2024-07-19 12:14 UTC, arnopo commented on README.md
> +
I would add following in readme to explain how to "emulate" on a Linux PC


## Run application  on a Linux PC ###
It is possible to run application on a Linux PC to communicate between two Linux processes.

```
  $ cd $PROJECT_ROOT/target
  $ echo "################### run ping test #####################"
  $ LD_LIBRARY_PATH=./lib  ./bin/rpmsg-echo-static &
  $ sleep 1
  $ LD_LIBRARY_PATH=./lib  ./bin//msg-test-rpmsg-ping-static 1
  $ 
  $ echo "################### run ping test #####################"
  $ LD_LIBRARY_PATH=./lib  ./bin/rpmsg-nocopy-echo-static &
  $ sleep 1
  $ LD_LIBRARY_PATH=./lib  ./bin//rpmsg-nocopy-ping-static  1
```

2024-07-23 21:08 UTC, tnmysh commented on README.md
> +
Correct, actually I can move this now too, as it shows how to build legacy apps.

2024-07-23 22:09 UTC, tnmysh commented on README.md
> +
Done.

2024-07-23 22:09 UTC, tnmysh commented on README.md
> +  $ make VERBOSE=1 install
Done.

2024-07-23 22:10 UTC, tnmysh commented on README.md
> +    $ make VERBOSE=1 install
Done.

2024-07-23 22:10 UTC, tnmysh commented on README.md
> +	-DCMAKE_INSTALL_PREFIX=<open_amp install dir>
Done.

2024-07-23 22:10 UTC, tnmysh commented on README.md
> +    $ cmake <libmetal_source> -DCMAKE_INSTALL_PREFIX=<libmetal install dir>
Done.

2024-07-23 22:10 UTC, tnmysh commented on README.md
> +```
Done.

2024-07-25 10:01 UTC, arnopo reviewed
few new comments
after addressing them LGTM

2024-07-25 10:01 UTC, arnopo commented on examples/legacy_apps/README.md
> +# Zephyr Example Application
Commit message to rework it does not reflect the commit.. could be splitted in 2 commits one for the yaml, one for the doc

2024-07-25 18:12 UTC, tnmysh commented on examples/legacy_apps/README.md
> +  $ LD_LIBRARY_PATH=./lib  ./bin/rpmsg-echo-static &
Actually yes, but I am addressing in this PR by explicitly mentioning -static flag.
I think with that flag, we should be building with static libraries correct?
I will have to test this.

2024-07-25 18:12 UTC, tnmysh commented on examples/legacy_apps/README.md
> +  $ LD_LIBRARY_PATH=./lib  ./bin/rpmsg-echo-static &
Just FYI, I haven't tested the steps in this README, I think it should be good that I test them now.

2024-07-25 18:13 UTC, tnmysh commented on examples/legacy_apps/README.md
> +# Zephyr Example Application
Okay I agree. Probably will remove this line too.

2024-07-31 21:54 UTC, tnmysh commented on examples/legacy_apps/README.md
> +  $ cmake . -Bbuild -DCMAKE_INSTALL_PREFIX= $PROJECT_ROOT/target
Done.

2024-07-31 21:54 UTC, tnmysh commented on examples/legacy_apps/README.md
> +  $ make -C build VERBOSE=1
Done.

2024-07-31 21:58 UTC, tnmysh commented on examples/legacy_apps/README.md
> +  $ LD_LIBRARY_PATH=./lib  ./bin/rpmsg-echo-static &
I looked into this. Looks like only passing -static isn't enough.

Some plumbing is needed in cmake infrastructure to make it work.

The issue is present on AMD platforms as well, but it doesn't affect development due to following reason:

1) tests directory isn't used in demos provided in petalinux.
2) static linkiing is happening only for remote firmware apps, and for that we have separate cmake infra that is used to build apps.

However, this issue should be fixed. I can work on that.

2024-08-01 12:53 UTC, arnopo approved these changes

2024-08-01 12:53 UTC, arnopo commented on examples/legacy_apps/README.md
> +  $ LD_LIBRARY_PATH=./lib  ./bin/rpmsg-echo-static &
yes issue is linked to the application build, not blocking to merge this series, can treated in a separate PR

2024-08-14 12:16 UTC, iuliana-prodan reviewed
This PR looks good but why do we call the folder `legacy_apps`?
When I read legacy app, I'm thinking of something old that might not even work - but maybe is just me :)
Can we call the folder `generic_samples`, or just `generic` (since it's already in examples).


Also, not very clear for me how these samples work?
Do we have a Linux-Zephyr communication?

Can we add, for each sample a README - like we have now [here](https://github.com/OpenAMP/openamp-system-reference/blob/main/examples/linux/rpmsg-mat-mul/README.md), for each app. 
I see the comment from the start of each sample (like [here](https://github.com/OpenAMP/openamp-system-reference/pull/44/files#diff-a1086a533ef9f1deda47d6a5e748c0558b9cdbe9c72a81ef376461cdefbcd159R6)) but IMO is not enough.

2024-08-15 15:56 UTC, tnmysh commented
> This PR looks good but why do we call the folder `legacy_apps`? When I read legacy app, I'm thinking of something old that might not even work - but maybe is just me :) Can we call the folder `generic_samples`, or just `generic` (since it's already in examples).

Some background on this:
So, These apps used to be in open-amp repository here: https://github.com/OpenAMP/open-amp/tree/main/apps
At that time openamp-system-reference repo did not exist. Now, we have separate repo available only for demos, we are moving demos from library repository.

Ideally, we want a framework that is easily portable to any platform and any OS. This framework isn't available yet. Many demos under "legacy_apps" are hardcoded to run only on AMD-Xilinx platforms. Eventually they will be deprecated. Hence the name "legacy_apps" makes sense.

We don't want to call it "generic" for the same reason, as not all demos are easily portable. Instead, we can introduce new demos under ${REPO}/examples/{OS}/ directory that is portable on all the platforms.

> 
> Also, not very clear for me how these samples work? Do we have a Linux-Zephyr communication?
> 

Some demos are using AMD-Xilinx BSP, and so they provide Linux-Baremetal, and Linux-FreeRTOS communication. Some demos provides Linux-Linux communication.
Linux-Linux RPMSG communicaiton is tested between two linux processes. 

> Can we add, for each sample a README - like we have now [here](https://github.com/OpenAMP/openamp-system-reference/blob/main/examples/linux/rpmsg-mat-mul/README.md), for each app. I see the comment from the start of each sample (like [here](https://github.com/OpenAMP/openamp-system-reference/pull/44/files#diff-a1086a533ef9f1deda47d6a5e748c0558b9cdbe9c72a81ef376461cdefbcd159R6)) but IMO is not enough.

Yes, we should add it, but it can be part of new PR and as enhancement. This PR only moves demos as it is, and makes sure they can be compiled. So, modifying cmake build infra as needed.

2024-08-15 20:27 UTC, tnmysh commented on examples/legacy_apps/cmake/modules/Findopen_amp.cmake
> +# Finidopen_amp
Fixed.

2024-08-15 20:28 UTC, tnmysh commented
@iuliana-prodan Thanks for reviews. Fixed comments.

2024-08-15 22:01 UTC, iuliana-prodan approved these changes

2024-08-28 07:05 UTC, merged