Unbind rpmsg dev
OpenAMP/openamp-system-reference pull request #45
Opened 2024-06-28 03:52 UTC by tnmysh

2024-07-02 08:54 UTC, arnopo commented
hi @tnmysh:  do you tried to use RPMSG_DESTROY_EPT_IOCTL instead?

2024-07-02 16:39 UTC, tnmysh commented
> hi @tnmysh: do you tried to use RPMSG_DESTROY_EPT_IOCTL instead?

Actually, I can do that in separate PR, where binding and unbinding both are taken care via IOCTLs, instead of writing to sysfs nodes. For now this PR is only fixing existing workflow.

2024-07-02 17:17 UTC, arnopo commented
> > hi @tnmysh: do you tried to use RPMSG_DESTROY_EPT_IOCTL instead?
> 
> Actually, I can do that in separate PR, where binding and unbinding both are taken care via IOCTLs, instead of writing to sysfs nodes. For now this PR is only fixing existing workflow.

you are right,  the bind is implemented in current exemples, so the unbind make sense

2024-07-02 17:20 UTC, arnopo commented on examples/linux/common/common.c
> +	return 0;
suggestion
```c
	ret = write(fd, rpmsg_dev_name, strlen(rpmsg_dev_name) + 1);
	close(fd);
	if (ret < 0) {
		fprintf(stderr, "Failed to write %s to %s, %s\n",
			rpmsg_dev_name, fpath, strerror(errno));
		return -EINVAL;
	}

	return 0;
```

2024-07-04 17:02 UTC, arnopo approved these changes
LGTM

2024-07-11 16:09 UTC, wmamills commented
As discussed in the rpmsg call today, the demos should work if the correct driver is already bound and in this case at least the driver should not be unbound.

If the driver DOES need to be bound, it is debatable if it should be unbound on exit or just leave it knowing that the person that needs something else can do the unbind themselves.

2024-07-18 21:25 UTC, tnmysh commented
> As discussed in the rpmsg call today, the demos should work if the correct driver is already bound and in this case at least the driver should not be unbound.
> 

Done.

2024-07-19 12:36 UTC, arnopo requested changes

2024-07-19 12:36 UTC, arnopo commented on examples/linux/common/common.c
> +			rpmsg_chdrv, fpath, strerror(errno));
it is a read , and in case of error `rpmsg_chdrv `is invalid

`fprintf(stderr, "Failed to read %s (%s)\n", fpath, strerror(errno));`

2024-07-19 12:36 UTC, arnopo commented on examples/linux/common/common.c
> +		close(fd);
the `close(fd)` can be moved just after `ret = read(fd, rpmsg_chdrv, sizeof(rpmsg_chdrv));` to avoid to duplicate it

2024-07-19 12:36 UTC, arnopo commented on examples/linux/rpmsg-echo-test/echo_test.c
> +	if (!is_rpmsg_chrdev_bind(rpmsg_dev)) {
The function is_rpmsg_chrdev_bind can return true, false or an error. Seems that the error case should be treated

2024-07-23 22:26 UTC, tnmysh commented on examples/linux/common/common.c
> +			rpmsg_chdrv, fpath, strerror(errno));
Ack.

2024-07-23 22:26 UTC, tnmysh commented on examples/linux/common/common.c
> +		close(fd);
Ack.

2024-07-24 01:26 UTC, tnmysh commented on examples/linux/rpmsg-echo-test/echo_test.c
> +	if (!is_rpmsg_chrdev_bind(rpmsg_dev)) {
Ack. Thanks for catching this.

2024-07-24 01:35 UTC, tnmysh commented on examples/linux/rpmsg-echo-test/echo_test.c
> +	if (!is_rpmsg_chrdev_bind(rpmsg_dev)) {
Also, I think is_rpmsg_chrdev_bind should be moved within bind_rpmsg_chrdev.
As it's common to all the apps.

2024-07-24 18:54 UTC, tnmysh commented on examples/linux/rpmsg-echo-test/echo_test.c
> +	if (!is_rpmsg_chrdev_bind(rpmsg_dev)) {
Done.

2024-07-25 11:32 UTC, arnopo approved these changes
with a minor comment

2024-07-25 11:32 UTC, arnopo commented on examples/linux/common/common.c
> +		printf("error: device %s is busy, drv bind=%s\n",
fprintf?

2024-07-25 15:36 UTC, tnmysh commented on examples/linux/common/common.c
> +		printf("error: device %s is busy, drv bind=%s\n",
done.

2024-07-29 15:05 UTC, tnmysh commented
@edmooring , @wmamills requesting reviews.

2024-08-07 16:38 UTC, tnmysh commented
@wmamills , created follow up issue here: https://github.com/OpenAMP/openamp-system-reference/issues/50

2024-08-15 20:39 UTC, wmamills commented
I have tested this with openamp-demo.
I first versified the failure mode:
docker run -it --rm openamp/demo-lite
qemu-zcu102 demo3
(login as root)
./demo3A
echo_test

This 2nd echo test fails. Likewise for demo3B and demo3C.

I then built a new image with openamp-ci-builds including this PR and updated the demo.
With the new image echo_test and mat_mul_demo can run multiple times after their associated demo script.

However ./demo3C followed by proxy_app continues to fail.
I belive this is because the proxy app firmware destroys its endpoint afterward and is not releated to this PR but this needs confirmation.

2024-08-15 22:30 UTC, tnmysh commented
@wmamills yes I confirm. There will be separate PR to fix that behavior.

Thanks.

2024-08-18 01:46 UTC, wmamills approved these changes
I have tested using openamp-demo demo3

2024-08-18 01:46 UTC, merged