examples: linux: cmdline support for rpmsg ctrl dev
OpenAMP/openamp-system-reference pull request #49
Opened 2024-07-18 15:22 UTC by rajimoha

Adding option -c for passing the rpmsg control device which the application needs to use.

Signe-off-by: Rajiv Mohan <rajiv.mohan@amd.com>

2024-07-19 12:45 UTC, arnopo approved these changes
LGTM

2024-07-24 15:33 UTC, tnmysh requested changes

2024-07-25 15:37 UTC, tnmysh approved these changes
LGTM.

2024-08-01 17:03 UTC, arnopo requested changes
checkpatch reports 2 issues:
sapace missing (see my comment
s/signe-off-by/signed-of-by/ in the commit message 

please fix before I merge it

2024-08-01 17:03 UTC, arnopo commented on examples/linux/rpmsg-echo-test/echo_test.c
> +			memset(rpmsg_ctrl_dev_name, 0,sizeof(rpmsg_ctrl_dev_name));
a space is missing before sizeof

2024-08-02 06:47 UTC, arnopo approved these changes

2024-08-02 06:48 UTC, merged