examples: Modify README formatting
OpenAMP/openamp-system-reference pull request #9
Opened 2022-12-12 00:59 UTC by TanmayShah-xilinx

Current README.md contains many titles with # prefix of each line. It generates lots of indexes when these README files are linked in openamp-docs repo.
Remove redundant # prefix. Only keep it for demo title, compilation steps and demo run steps. This way, openamp-docs generates minimal index in table of content.

Also re-edit README.md files for better presentation.

Signed-off-by: Tanmay Shah <tanmay.shah@amd.com>

2022-12-12 10:14 UTC, arnopo commented on examples/linux/rpmsg-echo-test/README.md
> +   console
s/console/console./

2022-12-12 10:14 UTC, arnopo commented on examples/linux/rpmsg-echo-test/README.md
> +     https://github.com/OpenAMP/open-amp/blob/main/apps/examples/echo/rpmsg-echo.c
Add bullet and format the link
`* based on  [rpmsg-echo.c](https://github.com/OpenAMP/open-amp/blob/main/apps/examples/echo/rpmsg-echo.c) example`

2022-12-12 10:14 UTC, arnopo commented on examples/linux/rpmsg-echo-test/README.md
> +   * Instructions to compile
you change the hierarchy here, seems strange to have the bullets below at same level.
suggestion s/* /## /

2022-12-12 10:14 UTC, arnopo commented on examples/linux/rpmsg-echo-test/README.md
> +   * This build step needs Xilinx Vendor specific toolchain xsdb
Any link to the toolchain xsdb?

2022-12-12 10:14 UTC, arnopo commented on examples/linux/rpmsg-mat-mul/README.md
> +# Demo: matrix multiply
I have same kind of remarks for this file too

2022-12-12 13:41 UTC, wmamills requested changes
Agree with Arnaud comments and added a couple myself.

2022-12-12 13:41 UTC, wmamills commented on examples/linux/rpmsg-echo-test/README.md
> +   * This build step needs Xilinx Vendor specific toolchain xsdb
Yes I had the same thought.  Does the user need to install the SDK?  I think that would be good to know at the start.

2022-12-12 19:53 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-echo-test/README.md
> +   * This build step needs Xilinx Vendor specific toolchain xsdb
Yes user will need to Install the Petalinux SDK. Rest of the information can be found on https://docs.xilinx.com/r/en-US/ug1186-zynq-openamp-gsg/Libmetal-and-OpenAMP-User-Guide
I will add hyper-link to above UserGuide.

2022-12-12 19:58 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-echo-test/README.md
> +   * Platform: Xilinx ZynqMP ZCU102 board
I will remove bullet point. But Ideas is to list all supported platforms. For now it is only ZynqMP.

2022-12-12 20:56 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-echo-test/README.md
> +   * Instructions to compile
I see what you mean. So, when I change hierarchy, I need to move indentation as well from the title. I will modify formatting for each README.md and keep 2 space of indentation and indent bullets and subtitles as required.

2022-12-12 20:59 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-echo-test/README.md
> +   * This build step needs Xilinx Vendor specific toolchain xsdb
I am sorry, it should have been xsdk i.e. petalinux SDK. That contains all the vendor specific binaries needed to build RPU firmware. Instructions to use petalinux with OpenAMP, can be found in UserGuide 1186, and Xilinx wiki. I will provide link to both.

2022-12-12 21:33 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-mat-mul/README.md
> +# Demo: matrix multiply
Sounds good. I will try to address same comments in all README.md for AMD-Xilinx Platform.

2022-12-12 23:13 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-echo-test/README.md
> +   * This build step needs Xilinx Vendor specific toolchain xsdb
It seems UG1186 is same as Xilinx wiki, so only providing link of Xilinx wiki page: https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/18841718/OpenAMP

2022-12-12 23:16 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-echo-test/README.md
> +   * Instructions to compile
I have to create subtitle line i.e. starts with ## and Bullet line i.e. starts with * at the same indent level for sphinx to generate Bullet point. Otherwise I don't see Bullet point. So, I will keep both at same indent level.

2022-12-12 23:33 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-mat-mul/README.md
> +     https://github.com/OpenAMP/open-amp#example-to-compile-zynq-ultrascale-mpsoc-r5-genericbaremetal-remote
Done.

2022-12-13 00:13 UTC, TanmayShah-xilinx commented on examples/linux/rpmsg-echo-test/README.md
> +     https://github.com/OpenAMP/open-amp/blob/main/apps/examples/echo/rpmsg-echo.c
Done

2022-12-13 10:28 UTC, arnopo approved these changes

2022-12-13 12:37 UTC, wmamills approved these changes
This looks good enough for now.
This has Xilinx everywhere and not AMD Xilinx.
If they need that changed it can be another PR

2022-12-13 12:41 UTC, merged